/**
 * Created by avivhatzir on 16/11/2015.
 */
Template.searchBoxForConnect.onCreated(function(){
  Session.set('googleResults',[{
    googleImg:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6EF2spkVH7zbM97BU_lIf8Tc2YsNk_I7mXT2PduNznOmVFNjYp2Der-E6',
    googleTitle: 'example',
    googleWebsiteName: 'www.example.com',
    googleDescription:"Example description"
  }]);
});

Template.searchBoxForConnect.helpers({

  //userCanAutoGenerateDotz: function(){
  //  let data = Template.parentData();
  //  if ( data.dot.ownerUserId === Meteor.userId() && data.dot.quickStartListId && data.dot.connectedDotzArray.length === 0 ) {
  //    return "colCenter";
  //  }
  //},
  googleResults: function(){
    return Session.get('googleResults');
  },
  dotzResult: function(){
    return Session.get('dotzResult');
  },

  dotzResultNumber: function(){
    if(Session.get('dotzResult')){
      return ("(" + Session.get('dotzResult').hits.length + ")");
    }
  },
  getDataForGoogleCard: function(){
    return {
      parentDotId:Template.parentData().dot._id,
      googleDot: this
    };
  },
  isAlreadyConnected: function(){
    return Modules.client.Dotz.canBeConnectedToDot(Template.parentData().dot._id, this._id)
  },
  dataForDotCard: function() {
    let connection = {
      connectedByUserId: this.ownerUserId,
      likes: "none"
    };

    let data = {
      dot: this,
      //ownerUser: Meteor.users.findOne(this.ownerUserId),
      connection: connection,
      inSearchResults: true
    };
    return data;
  }

});

Template.searchBoxForConnect.events({
  'submit ._googleSearch': function(e){
    e.preventDefault();
    Modules.client.googleCustomSearch($('#_searchBoxInput').val(), function(error, result){
      if (error){
        Bert.alert("We are poor and have only 100 queries per day, please do something with it.",'danger')
      }else{
        Session.set('googleResults', Modules.client.googleResultToCard(result));
      }
    });
  },
  'click ._createDot':function(){
    Session.set('parentDot', this.dot._id);
    Modal.show('createDotModal');
  },

  'click ._createList':function(){
    Session.set('parentDot', this.dot._id);
    Modal.show('createListModal');
  }
});

