CREATE_ACTION = "Create";
CONNECT_ACTION = "Connect";
LIKE_ACTION = "Like";
MAXIMUM_NUMBER_OF_FEED_DOTZ_TO_CHECK = 15;
ROLES = {
  FB_GROUP_ADMIN: "FBGroupAdmin",
  CONNECTOR: "Connector",
  FB_GROUP_MEMBER: "FBGroupMember",
  ADMIN: "Admin"
};
